array_layout = "Block"
array_width = 90
attributes_on_same_line_as_field = false
attributes_on_same_line_as_variant = false
chain_one_line_max = 90
chain_split_single_child = true
comment_width = 120
fn_call_width = 120
hard_tabs = false
max_width = 120
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
tab_spaces = 4
use_try_shorthand = true
