language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly

cache: cargo

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y firejail python
